version: '3'
services:
  database:
    image: postgres:17.7-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - ${STORAGE}/database:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.10.5
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=${HEDGEDOC_DOMAIN}
      - CMD_URL_ADDPORT=true
    volumes:
      - ${STORAGE}/uploads:/hedgedoc/public/uploads
    ports:
      - "${HEDGEDOC_PORT}:3000"
    restart: always
    depends_on:
      - database
