version: '3.8'

services:
  postgres-replica:
    image: bitnami/postgresql:latest
    container_name: postgres-replica
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: ${VW_PG_USER}
      POSTGRESQL_PASSWORD: ${VW_PG_PASSWORD}
      POSTGRESQL_DATABASE: vaultwarden
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: ${VW_PG_REPLICATION_USER}
      POSTGRESQL_REPLICATION_PASSWORD: ${VW_PG_REPLICATION_PASSWORD}
      POSTGRESQL_MASTER_HOST: ${VW_PG_MASTER_HOST}
      POSTGRESQL_MASTER_PORT_NUMBER: ${VW_PG_MASTER_PASSWORD}
    volumes:
      - ${STORAGE}/vaultwarden/postgres_data:/bitnami/postgresql
    networks:
      - vaultnet

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${VW_DOMAIN}
      DATABASE_URL: postgresql://${VW_PG_USER}:${VW_PG_PASSWORD}@postgres-replica:5432/vaultwarden
      ADMIN_TOKEN: ${VW_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: "false"
      SMTP_HOST: ${VW_SMTP_HOST}
      SMTP_PORT: ${VW_SMTP_PORT}
      SMTP_SECURITY: ${VW_SMTP_SECURITY}
      SMTP_USERNAME: ${VW_SMTP_USER}
      SMTP_PASSWORD: ${VW_SMTP_PASSWORD}
      SMTP_FROM: ${VW_SMTP_USER}
      SMTP_FROM_NAME: "Vaultwarden"
    volumes:
      - ${STORAGE}/vaultwarden/vw-data:/data
    ports:
      - "8200:80"
    depends_on:
      - postgres-replica
    networks:
      - vaultnet

networks:
  vaultnet:
    driver: bridge
