services:
  db:
    image: postgres:15
    ports:
      - 5433:5432
    volumes:
      - "${STORAGE}/claper-db:/var/lib/postgresql/data"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "claper"
        - "-U"
        - "claper"
      retries: 3
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
    networks:
      - claper-net
  app:
    image: ghcr.io/claperco/claper:latest # or build: .
    ports:
      - 4000:4000
    volumes:
      - "${STORAGE}/claper-uploads:/app/uploads"
    healthcheck:
      test: curl --fail http://localhost:4000 || exit 1
      retries: 3
      start_period: 20s
      timeout: 5s
    environment:
      - BASE_URL=${CLAPER_BASE_URL}
      - PRESENTATION_STORAGE=local
      - PRESENTATION_STORAGE_DIR=/app/uploads
      - SECRET_KEY_BASE=${CLAPER_SECRET_KEY_BASE}
      - DATABASE_URL=postgres://claper:claper@db:5432/claper
    depends_on:
      db:
        condition: service_healthy
    networks:
      - claper-net

networks:
  claper-net:
    driver: bridge
